package com.wealthflow.app.presentation.theme

import androidx.compose.ui.graphics.Color

// Mapped 1:1 from the WealthFlow HTML mockup's tailwind.config color tokens (light theme)
val Primary = Color(0xFF003527)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF064E3B)
val OnPrimaryContainer = Color(0xFF80BEA6)
val PrimaryFixed = Color(0xFFB0F0D6)
val PrimaryFixedDim = Color(0xFF95D3BA)
val InversePrimary = Color(0xFF95D3BA)

val Secondary = Color(0xFF565E74)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFDAE2FD)
val OnSecondaryContainer = Color(0xFF5C647A)
val SecondaryFixed = Color(0xFFDAE2FD)
val SecondaryFixedDim = Color(0xFFBEC6E0)

val Tertiary = Color(0xFF003623)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF004F34)
val OnTertiaryContainer = Color(0xFF31C98F)
val TertiaryFixed = Color(0xFF6FFBBE)
val TertiaryFixedDim = Color(0xFF4EDEA3)

val Background = Color(0xFFF8F9FF)
val OnBackground = Color(0xFF0B1C30)
val Surface = Color(0xFFF8F9FF)
val OnSurface = Color(0xFF0B1C30)
val SurfaceVariant = Color(0xFFD3E4FE)
val OnSurfaceVariant = Color(0xFF404944)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFEFF4FF)
val SurfaceContainer = Color(0xFFE5EEFF)
val SurfaceContainerHigh = Color(0xFFDCE9FF)
val SurfaceContainerHighest = Color(0xFFD3E4FE)
val SurfaceBright = Color(0xFFF8F9FF)
val SurfaceDim = Color(0xFFCBDBF5)
val Outline = Color(0xFF707974)
val OutlineVariant = Color(0xFFBFC9C3)
val InverseSurface = Color(0xFF213145)
val InverseOnSurface = Color(0xFFEAF1FF)

val ErrorColor = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
